// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: subtraction.proto

package subtraction

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MinusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Number        int32 `protobuf:"varint,1,opt,name=number,proto3" json:"number,omitempty"`
	AnotherNumber int32 `protobuf:"varint,2,opt,name=anotherNumber,proto3" json:"anotherNumber,omitempty"`
}

func (x *MinusRequest) Reset() {
	*x = MinusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subtraction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinusRequest) ProtoMessage() {}

func (x *MinusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_subtraction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinusRequest.ProtoReflect.Descriptor instead.
func (*MinusRequest) Descriptor() ([]byte, []int) {
	return file_subtraction_proto_rawDescGZIP(), []int{0}
}

func (x *MinusRequest) GetNumber() int32 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *MinusRequest) GetAnotherNumber() int32 {
	if x != nil {
		return x.AnotherNumber
	}
	return 0
}

type MinusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Subtract int64 `protobuf:"varint,1,opt,name=subtract,proto3" json:"subtract,omitempty"`
}

func (x *MinusResponse) Reset() {
	*x = MinusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_subtraction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MinusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinusResponse) ProtoMessage() {}

func (x *MinusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_subtraction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinusResponse.ProtoReflect.Descriptor instead.
func (*MinusResponse) Descriptor() ([]byte, []int) {
	return file_subtraction_proto_rawDescGZIP(), []int{1}
}

func (x *MinusResponse) GetSubtract() int64 {
	if x != nil {
		return x.Subtract
	}
	return 0
}

var File_subtraction_proto protoreflect.FileDescriptor

var file_subtraction_proto_rawDesc = []byte{
	0x0a, 0x11, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x4c, 0x0a, 0x0c, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0d, 0x61, 0x6e, 0x6f, 0x74,
	0x68, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0d, 0x61, 0x6e, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22, 0x2b,
	0x0a, 0x0d, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x32, 0x4f, 0x0a, 0x0b, 0x53,
	0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x40, 0x0a, 0x05, 0x4d, 0x69,
	0x6e, 0x75, 0x73, 0x12, 0x19, 0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x4d, 0x69, 0x6e, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a,
	0x2e, 0x73, 0x75, 0x62, 0x74, 0x72, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x4d, 0x69, 0x6e,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_subtraction_proto_rawDescOnce sync.Once
	file_subtraction_proto_rawDescData = file_subtraction_proto_rawDesc
)

func file_subtraction_proto_rawDescGZIP() []byte {
	file_subtraction_proto_rawDescOnce.Do(func() {
		file_subtraction_proto_rawDescData = protoimpl.X.CompressGZIP(file_subtraction_proto_rawDescData)
	})
	return file_subtraction_proto_rawDescData
}

var file_subtraction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_subtraction_proto_goTypes = []interface{}{
	(*MinusRequest)(nil),  // 0: subtraction.MinusRequest
	(*MinusResponse)(nil), // 1: subtraction.MinusResponse
}
var file_subtraction_proto_depIdxs = []int32{
	0, // 0: subtraction.Subtraction.Minus:input_type -> subtraction.MinusRequest
	1, // 1: subtraction.Subtraction.Minus:output_type -> subtraction.MinusResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_subtraction_proto_init() }
func file_subtraction_proto_init() {
	if File_subtraction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_subtraction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_subtraction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MinusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_subtraction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_subtraction_proto_goTypes,
		DependencyIndexes: file_subtraction_proto_depIdxs,
		MessageInfos:      file_subtraction_proto_msgTypes,
	}.Build()
	File_subtraction_proto = out.File
	file_subtraction_proto_rawDesc = nil
	file_subtraction_proto_goTypes = nil
	file_subtraction_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SubtractionClient is the client API for Subtraction service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SubtractionClient interface {
	Minus(ctx context.Context, in *MinusRequest, opts ...grpc.CallOption) (*MinusResponse, error)
}

type subtractionClient struct {
	cc grpc.ClientConnInterface
}

func NewSubtractionClient(cc grpc.ClientConnInterface) SubtractionClient {
	return &subtractionClient{cc}
}

func (c *subtractionClient) Minus(ctx context.Context, in *MinusRequest, opts ...grpc.CallOption) (*MinusResponse, error) {
	out := new(MinusResponse)
	err := c.cc.Invoke(ctx, "/subtraction.Subtraction/Minus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SubtractionServer is the server API for Subtraction service.
type SubtractionServer interface {
	Minus(context.Context, *MinusRequest) (*MinusResponse, error)
}

// UnimplementedSubtractionServer can be embedded to have forward compatible implementations.
type UnimplementedSubtractionServer struct {
}

func (*UnimplementedSubtractionServer) Minus(context.Context, *MinusRequest) (*MinusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Minus not implemented")
}

func RegisterSubtractionServer(s *grpc.Server, srv SubtractionServer) {
	s.RegisterService(&_Subtraction_serviceDesc, srv)
}

func _Subtraction_Minus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SubtractionServer).Minus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/subtraction.Subtraction/Minus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SubtractionServer).Minus(ctx, req.(*MinusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Subtraction_serviceDesc = grpc.ServiceDesc{
	ServiceName: "subtraction.Subtraction",
	HandlerType: (*SubtractionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Minus",
			Handler:    _Subtraction_Minus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "subtraction.proto",
}
